In [1]:
import numpy as np

### Functions For Creating Arrays in Numpy
#### 1. array()
#### 2. linspace()
#### 3. logspace()
#### 4. arange()
#### 5. zeros()
#### 6. omes()
#### 7. eye()
#### 8. random.rand()


### 1. array()

###### Array is a group of Similar elements

###### Array Supports indexing, Slicing , Duplicate Values, 
###### Arrays are muttable


In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
arr = np.array([1,2,3,4,5])
arr[0:3]

array([1, 2, 3])

### Properties Of Numpy Array

In [4]:
arr.ndim  # Dimension of numpy Array

1

In [5]:
arr.shape # How many elements present in each dimension

(5,)

In [6]:
arr.size #No. of elements in entire array

5

In [7]:
arr.dtype # Data type of elements

dtype('int32')

##### So if we know the capacity or maximum value of the data then change the type of data accordingly which can help reducing the size of data

In [8]:
arr.nbytes # Gives the total number of bytes consumed by the elements of the numpy array

20

##### If we change int32 to int8 we can see the difference

In [9]:
arr = arr.astype("int8") #Converts one Data type to another Data type

In [10]:
arr.nbytes

5

##### Previously it had taken 20 bytes,But when we changed int32 to int8 . now its only taking 5 bytes

In [11]:
arr2 = np.array([5,6,8,8,10],dtype="int8") #We can also specify the datatype during the assignment

##### This is called quantization( Reducing the number of bytes data taking in the memmory)

In [12]:
# Example
arr3 = np.array([4,5,6,7,8,400],dtype="int8")
arr

array([1, 2, 3, 4, 5], dtype=int8)

In [13]:
arr4 = np.array([4.3,5,6,7,8,400])
arr4.dtype


dtype('float64')

##### Array is a collection of similar elements . So if there is one disimilar element in the array then all the elements in the array will be converted to the largest datatype

In [14]:
arr5  = np.array([1,2,3,"manu"])
arr5

array(['1', '2', '3', 'manu'], dtype='<U11')

In [15]:
arr5.dtype

dtype('<U11')

In [16]:
arr5.astype("<U4")

array(['1', '2', '3', 'manu'], dtype='<U4')

###### It only need the number of bytes , that is needed for the largest element in the array to store in memory, Here largest element is "manu" which requires only 4 bytes 

In [17]:
arr5 = arr5.astype("<U3")
arr5

array(['1', '2', '3', 'man'], dtype='<U3')

In [18]:
# Another Example
arr6 = np.array(["Python","Java","Ruby","Rust"])

In [19]:
arr6.dtype

dtype('<U6')

In [20]:
arr7 = np.array([16,1,16,1,2,3,4,4,4,5,16])

###  Array Slicing & Indexing

In [21]:
arr7[-1] #last Index

16

In [22]:
arr7[1:6]

array([ 1, 16,  1,  2,  3])

In [23]:
arr7[2] = 100 # Array is muttable
arr7

array([ 16,   1, 100,   1,   2,   3,   4,   4,   4,   5,  16])

### Adding and Deleting Elements

##### append() add elements to the end of the array

In [24]:
arr7 = np.append(arr7, 6) # Appending one element 
arr7

array([ 16,   1, 100,   1,   2,   3,   4,   4,   4,   5,  16,   6])

In [25]:
arr7 = np.append(arr7,[2,3,4,7,19]) # Appeding multiple elements
arr7

array([ 16,   1, 100,   1,   2,   3,   4,   4,   4,   5,  16,   6,   2,
         3,   4,   7,  19])

###### To Insert element at a particular position -> insert(arr,index,value)

In [26]:
arr7 = np.insert(arr7,5,189)
arr7

array([ 16,   1, 100,   1,   2, 189,   3,   4,   4,   4,   5,  16,   6,
         2,   3,   4,   7,  19])

In [27]:
arr7 = np.insert(arr7,2,[5,6,7,8])
arr7

array([ 16,   1,   5,   6,   7,   8, 100,   1,   2, 189,   3,   4,   4,
         4,   5,  16,   6,   2,   3,   4,   7,  19])

##### To find the index of a element based on a condion -> where(condition)

In [28]:
np.where(arr7==3)

(array([10, 18], dtype=int64),)

In [29]:
np.where(arr7==3)[0][0] # To get the first index of the element 

10

In [30]:
np.where(arr7 < 5) # Index of elements whose value is less than 5

(array([ 1,  7,  8, 10, 11, 12, 13, 17, 18, 19], dtype=int64),)

In [31]:
np.where(arr7 < 5)

(array([ 1,  7,  8, 10, 11, 12, 13, 17, 18, 19], dtype=int64),)

###### Delete an element from array (Based on Index)-> delete(array_name,index)

In [32]:
np.delete(arr7,1) # Element at 1st Index is removed

array([ 16,   5,   6,   7,   8, 100,   1,   2, 189,   3,   4,   4,   4,
         5,  16,   6,   2,   3,   4,   7,  19])

###### Delete an element from array (Based on Value)

In [33]:
np.where(arr7 == 7)[0][0] 

4

In [34]:
arr7=np.delete(arr7,np.where(arr7 == 7)[0][0]) #Delete a single element
arr7

array([ 16,   1,   5,   6,   8, 100,   1,   2, 189,   3,   4,   4,   4,
         5,  16,   6,   2,   3,   4,   7,  19])

In [35]:
arr7=np.delete(arr7,np.where(arr7==4)) # Removing All the occurence of 4
arr7

array([ 16,   1,   5,   6,   8, 100,   1,   2, 189,   3,   5,  16,   6,
         2,   3,   7,  19])

####  Boolean Indexing (Filters)

In [36]:
arr8 = np.array([16,1,16,1,2,3,3,3,4,56,16])

In [37]:
arr8 == 16 # Where ever we have 16 it returns True

array([ True, False,  True, False, False, False, False, False, False,
       False,  True])

In [38]:
arr8[arr8==16] # Gives value

array([16, 16, 16])

In [39]:
arr8<5  # Based On Condition Returns True for elements which is less than 5

array([False,  True, False,  True,  True,  True,  True,  True,  True,
       False, False])

In [40]:
arr8[arr8<5] # Gives elements which is less than 5

array([1, 1, 2, 3, 3, 3, 4])

###### Multiple Condtion In Boolean Indexing

In [41]:
(arr8 > 20) & (arr8 < 60) # Index of elements which are greater than 20 and less than 60

array([False, False, False, False, False, False, False, False, False,
        True, False])

In [42]:
arr8[(arr8 > 20) & (arr8 < 60)]

array([56])

### 2D Array

In [43]:
arr9 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [44]:
arr9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
arr9.ndim

2

In [46]:
arr9.shape  

(3, 4)

In [47]:
arr9.size # Total Number of elements in the array

12

In [48]:
arr10 =  np.array([[1,2,3,4],[5,6,7,8],[9,10,12],[1,2,3,4],[5,6,7,8],[9,11,12]])

C:\Users\MANU\AppData\Local\Temp/ipykernel_7868/287533534.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr10 =  np.array([[1,2,3,4],[5,6,7,8],[9,10,12],[1,2,3,4],[5,6,7,8],[9,11,12]])


In [49]:
arr10

array([list([1, 2, 3, 4]), list([5, 6, 7, 8]), list([9, 10, 12]),
       list([1, 2, 3, 4]), list([5, 6, 7, 8]), list([9, 11, 12])],
      dtype=object)

In [50]:
arr10.dtype

dtype('O')

In [51]:
arr10 =  np.array([[1,2,3,4],[5,6,7,8],[9,10,12,np.nan],[1,2,3,4],[5,6,7,8],[9,11,12,np.nan]])

In [52]:
arr10

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 12., nan],
       [ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 11., 12., nan]])

In [53]:
arr10.dtype

dtype('float64')

###  Slicing of 2D Arrays

In [54]:
arr10

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 12., nan],
       [ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 11., 12., nan]])

In [55]:
arr10[3,2] # Specific Element ( Element in 4th row and 3rd Column)

3.0

In [56]:
arr10[2] # Specific row (Getting the elements of 3rd row)

array([ 9., 10., 12., nan])

In [57]:
arr10[2,:2] # Slicing a specific row ( Here we are slicing the 3rd row)

array([ 9., 10.])

In [58]:
arr10[1:3,2] # Slicing a specific column(Here slicing the 3rd column)

array([ 7., 12.])

In [59]:
arr10[:,1] # Slicing the entire column from the array

array([ 2.,  6., 10.,  2.,  6., 11.])

In [60]:
arr10[0,:] # Slicing the first row

array([1., 2., 3., 4.])

In [61]:
arr10[-1,:] # Slicing the last row

array([ 9., 11., 12., nan])

### Handling Exponentional Values

In [62]:
arr11 = np.array([[ 1,  2,  3,  4],
       [ 5,  6,  7.54,  8],
       [ 9, 10, 12.1, np.nan],
       [ 1.456,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9.542, 11, 12, np.nan],
       [ 1456,4563,23,234.567],
       [4453,6.78,25,78]])

In [63]:
arr11

array([[1.00000e+00, 2.00000e+00, 3.00000e+00, 4.00000e+00],
       [5.00000e+00, 6.00000e+00, 7.54000e+00, 8.00000e+00],
       [9.00000e+00, 1.00000e+01, 1.21000e+01,         nan],
       [1.45600e+00, 2.00000e+00, 3.00000e+00, 4.00000e+00],
       [5.00000e+00, 6.00000e+00, 7.00000e+00, 8.00000e+00],
       [9.54200e+00, 1.10000e+01, 1.20000e+01,         nan],
       [1.45600e+03, 4.56300e+03, 2.30000e+01, 2.34567e+02],
       [4.45300e+03, 6.78000e+00, 2.50000e+01, 7.80000e+01]])

In [64]:
np.set_printoptions(precision=2,suppress=True) 

# Here precision indicates the number of elements after decimal point
# and suppress = True -> Supress all the remaining digits after the decimal point

In [65]:
arr11

array([[   1.  ,    2.  ,    3.  ,    4.  ],
       [   5.  ,    6.  ,    7.54,    8.  ],
       [   9.  ,   10.  ,   12.1 ,     nan],
       [   1.46,    2.  ,    3.  ,    4.  ],
       [   5.  ,    6.  ,    7.  ,    8.  ],
       [   9.54,   11.  ,   12.  ,     nan],
       [1456.  , 4563.  ,   23.  ,  234.57],
       [4453.  ,    6.78,   25.  ,   78.  ]])

In [66]:
arr11[3:7,2]

array([ 3.,  7., 12., 23.])

In [67]:
# arr11[3:7,2] arr11[:3,0]

### 3D Array

In [68]:
arr12 = np.array([
    [[ 1,  2,  3,  4],
     [ 5,  6,  7,  8],
     [ 9, 10, 11, 12]],
    
    [[ 5,  2,  13,  4],
     [ 6,  6,  7,  8],
     [ 9, 15, 11, 12]],
    
    [[ 11,  2,  9,  4],
     [ 5,  23,  17,  8],
     [ 9, 10, 11, 12]]
])

In [69]:
arr12

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 5,  2, 13,  4],
        [ 6,  6,  7,  8],
        [ 9, 15, 11, 12]],

       [[11,  2,  9,  4],
        [ 5, 23, 17,  8],
        [ 9, 10, 11, 12]]])

In [70]:
arr12.shape 

(3, 3, 4)

In [71]:
arr12.size

36

In [72]:
arr12.ndim

3

###### Slicing 3D Array


In [73]:
# Syntax arr[1st Dimesnion,2nd Dimension,3rd Dimension]

arr12[1:3,1,2:]

array([[ 7,  8],
       [17,  8]])

######  Convert  a Muti Dimensional Array to Single Dimensional - flatten()

In [74]:
arr13 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [75]:
arr13

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [76]:
arr13.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

###### Converting Any Dimension to Other Dimension - reshape()

In [77]:
arr14 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr14

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
arr14.shape

(3, 4)

In [79]:
arr14.size

12

In [80]:
arr14.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [81]:
arr14.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

## arange()

In [82]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

###### Disadvantage of range() is we can't give float value as step size. Also we can give start(minimum) and end (maximum) value as a float number

###### range(1.3,5,.1) -> Raise an error

######  arange(minimum_value,maximum_value,step_size)

In [83]:
np.arange(1.5,2.3,.1)

array([1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2])

In [84]:
np.arange(0,10,1.5)

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

###### If we don't give any third parameter(step_size) in arange() , By default  value will be 1

In [85]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## linspace()

###### syntax - > linspace(min_value,max_value,no_of_elements)

Returns the specified number elemnets(no_of_elements) between max value and min value with equal difference(Equally Spaced) between elements. max_value is inclusive

In [86]:
np.linspace(10,20,6)

array([10., 12., 14., 16., 18., 20.])

In [87]:
np.linspace(10,20,7)

array([10.  , 11.67, 13.33, 15.  , 16.67, 18.33, 20.  ])

In [88]:
np.linspace(1,2,100)

array([1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09, 1.1 ,
       1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 , 1.21,
       1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31, 1.32,
       1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42, 1.43,
       1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.51, 1.52, 1.53, 1.54, 1.55,
       1.56, 1.57, 1.58, 1.59, 1.6 , 1.61, 1.62, 1.63, 1.64, 1.65, 1.66,
       1.67, 1.68, 1.69, 1.7 , 1.71, 1.72, 1.73, 1.74, 1.75, 1.76, 1.77,
       1.78, 1.79, 1.8 , 1.81, 1.82, 1.83, 1.84, 1.85, 1.86, 1.87, 1.88,
       1.89, 1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96, 1.97, 1.98, 1.99,
       2.  ])

In [89]:
np.linspace(10,20,7,endpoint=False) # endpoint=False -> Then Upper Limit(Max Value) is not inculded

array([10.  , 11.43, 12.86, 14.29, 15.71, 17.14, 18.57])

###### If we don't give any third parameter(No_of_elements) in linspace() , By default  value will be 50 

In [90]:
np.linspace(10,20)

array([10.  , 10.2 , 10.41, 10.61, 10.82, 11.02, 11.22, 11.43, 11.63,
       11.84, 12.04, 12.24, 12.45, 12.65, 12.86, 13.06, 13.27, 13.47,
       13.67, 13.88, 14.08, 14.29, 14.49, 14.69, 14.9 , 15.1 , 15.31,
       15.51, 15.71, 15.92, 16.12, 16.33, 16.53, 16.73, 16.94, 17.14,
       17.35, 17.55, 17.76, 17.96, 18.16, 18.37, 18.57, 18.78, 18.98,
       19.18, 19.39, 19.59, 19.8 , 20.  ])

## zeros()

###### To create a numpy array with all zeros

In [91]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [92]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

## ones()

In [93]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## eye()

######  For creating identity matrix

In [94]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [95]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

## random.rand()


###### For creating array with random elements

In [96]:
np.random.randint(0,10) # Returns a random number between 0 and 10

1

In [97]:
np.random.randint(0,10,size=(3,4))

array([[6, 7, 9, 7],
       [4, 0, 0, 4],
       [2, 3, 7, 4]])

### Arithemetic operations on array

###### For doing arithemetic operations arrays must be of same size

In [98]:
a = np.array([[1,2,3,4],[13,12,33,43]])

In [99]:
b = np.array([[4,5,2,5],[2,4,5,7]])

In [100]:
a.shape

(2, 4)

In [101]:
b.shape

(2, 4)

In [102]:
a + b # Adding two elements

array([[ 5,  7,  5,  9],
       [15, 16, 38, 50]])

In [103]:
a - b

array([[-3, -3,  1, -1],
       [11,  8, 28, 36]])

In [104]:
a /b

array([[0.25, 0.4 , 1.5 , 0.8 ],
       [6.5 , 3.  , 6.6 , 6.14]])

In [105]:
a*b

array([[  4,  10,   6,  20],
       [ 26,  48, 165, 301]])

In [106]:
a**b

array([[         1,         32,          9,       1024],
       [       169,      20736,   39135393, 1235671459]], dtype=int32)

####  Cocatenate

In [107]:
np.concatenate([a,b]) # Cocatenating row wise

array([[ 1,  2,  3,  4],
       [13, 12, 33, 43],
       [ 4,  5,  2,  5],
       [ 2,  4,  5,  7]])

In [108]:
np.concatenate([a,b],axis=1) # Cocatenating column wise

array([[ 1,  2,  3,  4,  4,  5,  2,  5],
       [13, 12, 33, 43,  2,  4,  5,  7]])

In [109]:
c = np.array([[1,2,3,4],[13,12,33,43]])
c

array([[ 1,  2,  3,  4],
       [13, 12, 33, 43]])

In [110]:
d = np.array([[4,5,2,5]])
d

array([[4, 5, 2, 5]])

In [111]:
np.concatenate([c,d])

array([[ 1,  2,  3,  4],
       [13, 12, 33, 43],
       [ 4,  5,  2,  5]])

In [112]:
# np.concatenate([c,d],axis=1) -> it will raise an error Becacuse we have different number of rows

###  Transpose of a matrix

In [113]:
a.T # Gives the Transpose of the array

array([[ 1, 13],
       [ 2, 12],
       [ 3, 33],
       [ 4, 43]])

In [114]:
np.transpose(a) # Gives the transpose of array

array([[ 1, 13],
       [ 2, 12],
       [ 3, 33],
       [ 4, 43]])