In [1]:
import numpy as np

### Functions For Creating Arrays in Numpy
#### 1. array()
#### 2. linspace()
#### 3. logspace()
#### 4. arange()
#### 5. zeros()
#### 6. omes()
#### 7. eye()
#### 8. random.rand()


### 1. array()

###### Array is a group of Similar elements

###### Array Supports indexing, Slicing , Duplicate Values, 
###### Arrays are muttable


In [2]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
arr = np.array([1,2,3,4,5])
arr[0:3]

array([1, 2, 3])

### Properties Of Numpy Array

In [4]:
arr.ndim  # Dimension of numpy Array

1

In [5]:
arr.shape # How many elements present in each dimension

(5,)

In [6]:
arr.size #No. of elements in entire array

5

In [7]:
arr.dtype # Data type of elements

dtype('int32')

##### So if we know the capacity or maximum value of the data then change the type of data accordingly which can help reducing the size of data

In [8]:
arr.nbytes # Gives the total number of bytes consumed by the elements of the numpy array

20

##### If we change int32 to int8 we can see the difference

In [9]:
arr = arr.astype("int8") #Converts one Data type to another Data type

In [10]:
arr.nbytes

5

##### Previously it had taken 20 bytes,But when we changed int32 to int8 . now its only taking 5 bytes

In [11]:
arr2 = np.array([5,6,8,8,10],dtype="int8") #We can also specify the datatype during the assignment

##### This is called quantization( Reducing the number of bytes data taking in the memmory)

In [12]:
# Example
arr3 = np.array([4,5,6,7,8,400],dtype="int8")
arr

array([1, 2, 3, 4, 5], dtype=int8)

In [13]:
arr4 = np.array([4.3,5,6,7,8,400])
arr4.dtype


dtype('float64')

##### Array is a collection of similar elements . So if there is one disimilar element in the array then all the elements in the array will be converted to the largest datatype

In [14]:
arr5  = np.array([1,2,3,"manu"])
arr5

array(['1', '2', '3', 'manu'], dtype='<U11')

In [15]:
arr5.dtype

dtype('<U11')

In [16]:
arr5.astype("<U4")

array(['1', '2', '3', 'manu'], dtype='<U4')

###### It only need the number of bytes , that is needed for the largest element in the array to store in memory, Here largest element is "manu" which requires only 4 bytes 

In [17]:
arr5 = arr5.astype("<U3")
arr5

array(['1', '2', '3', 'man'], dtype='<U3')

In [18]:
# Another Example
arr6 = np.array(["Python","Java","Ruby","Rust"])

In [19]:
arr6.dtype

dtype('<U6')

In [20]:
arr7 = np.array([16,1,16,1,2,3,4,4,4,5,16])

###  Array Slicing & Indexing

In [21]:
arr7[-1] #last Index

16

In [22]:
arr7[1:6]

array([ 1, 16,  1,  2,  3])

In [23]:
arr7[2] = 100 # Array is muttable
arr7

array([ 16,   1, 100,   1,   2,   3,   4,   4,   4,   5,  16])

### Adding and Deleting Elements

##### append() add elements to the end of the array

In [24]:
arr7 = np.append(arr7, 6) # Appending one element 
arr7

array([ 16,   1, 100,   1,   2,   3,   4,   4,   4,   5,  16,   6])

In [25]:
arr7 = np.append(arr7,[2,3,4,7,19]) # Appeding multiple elements
arr7

array([ 16,   1, 100,   1,   2,   3,   4,   4,   4,   5,  16,   6,   2,
         3,   4,   7,  19])

###### To Insert element at a particular position -> insert(arr,index,value)

In [26]:
arr7 = np.insert(arr7,5,189)
arr7

array([ 16,   1, 100,   1,   2, 189,   3,   4,   4,   4,   5,  16,   6,
         2,   3,   4,   7,  19])

In [27]:
arr7 = np.insert(arr7,2,[5,6,7,8])
arr7

array([ 16,   1,   5,   6,   7,   8, 100,   1,   2, 189,   3,   4,   4,
         4,   5,  16,   6,   2,   3,   4,   7,  19])

##### To find the index of a element based on a condion -> where(condition)

In [28]:
np.where(arr7==3)

(array([10, 18], dtype=int64),)

In [29]:
np.where(arr7==3)[0][0] # To get the first index of the element 

10

In [30]:
np.where(arr7 < 5) # Index of elements whose value is less than 5

(array([ 1,  7,  8, 10, 11, 12, 13, 17, 18, 19], dtype=int64),)

In [31]:
np.where(arr7 < 5)

(array([ 1,  7,  8, 10, 11, 12, 13, 17, 18, 19], dtype=int64),)

###### Delete an element from array (Based on Index)-> delete(array_name,index)

In [32]:
np.delete(arr7,1) # Element at 1st Index is removed

array([ 16,   5,   6,   7,   8, 100,   1,   2, 189,   3,   4,   4,   4,
         5,  16,   6,   2,   3,   4,   7,  19])

###### Delete an element from array (Based on Value)

In [33]:
np.where(arr7 == 7)[0][0] 

4

In [34]:
arr7=np.delete(arr7,np.where(arr7 == 7)[0][0]) #Delete a single element
arr7

array([ 16,   1,   5,   6,   8, 100,   1,   2, 189,   3,   4,   4,   4,
         5,  16,   6,   2,   3,   4,   7,  19])

In [35]:
arr7=np.delete(arr7,np.where(arr7==4)) # Removing All the occurence of 4
arr7

array([ 16,   1,   5,   6,   8, 100,   1,   2, 189,   3,   5,  16,   6,
         2,   3,   7,  19])

####  Boolean Indexing (Filters)

In [36]:
arr8 = np.array([16,1,16,1,2,3,3,3,4,56,16])

In [37]:
arr8 == 16 # Where ever we have 16 it returns True

array([ True, False,  True, False, False, False, False, False, False,
       False,  True])

In [38]:
arr8[arr8==16] # Gives value

array([16, 16, 16])

In [39]:
arr8<5  # Based On Condition Returns True for elements which is less than 5

array([False,  True, False,  True,  True,  True,  True,  True,  True,
       False, False])

In [40]:
arr8[arr8<5] # Gives elements which is less than 5

array([1, 1, 2, 3, 3, 3, 4])

###### Multiple Condtion In Boolean Indexing

In [41]:
(arr8 > 20) & (arr8 < 60) # Index of elements which are greater than 20 and less than 60

array([False, False, False, False, False, False, False, False, False,
        True, False])

In [42]:
arr8[(arr8 > 20) & (arr8 < 60)]

array([56])

### 2D Array

In [43]:
arr9 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [44]:
arr9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
arr9.ndim

2

In [46]:
arr9.shape  

(3, 4)

In [47]:
arr9.size # Total Number of elements in the array

12

In [48]:
arr10 =  np.array([[1,2,3,4],[5,6,7,8],[9,10,12],[1,2,3,4],[5,6,7,8],[9,11,12]])

C:\Users\MANU\AppData\Local\Temp/ipykernel_6968/287533534.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr10 =  np.array([[1,2,3,4],[5,6,7,8],[9,10,12],[1,2,3,4],[5,6,7,8],[9,11,12]])


In [49]:
arr10

array([list([1, 2, 3, 4]), list([5, 6, 7, 8]), list([9, 10, 12]),
       list([1, 2, 3, 4]), list([5, 6, 7, 8]), list([9, 11, 12])],
      dtype=object)

In [50]:
arr10.dtype

dtype('O')

In [51]:
arr10 =  np.array([[1,2,3,4],[5,6,7,8],[9,10,12,np.nan],[1,2,3,4],[5,6,7,8],[9,11,12,np.nan]])

In [52]:
arr10

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 12., nan],
       [ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 11., 12., nan]])

In [53]:
arr10.dtype

dtype('float64')